### ISSUE TITLE
NuGet packages for 1.1 cause MSBuild warnings

### ISSUE THREAD

**Issue by Spongman** [atifaziz/Fizzler#63]
- new c# .net 4.7  console app
- install-package Fizzler.Systems.HtmlAgilityPack
- build

> C:\vs15\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Fizzler.Systems.HtmlAgilityPack, Version=1.1.21209.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

**Comment by atifaziz** [comment]
I don't have .NET 4.7 so is this something you can help investigate and find what's the issue with the packages. I'm afraid I don't have much to go by with given the steps you listed and the warning you quoted.

**Comment by atifaziz** [comment]
Looks like this may have nothing to do with which version of .NET Framework you target. I tried with 4.6 and got a warning as well, except it's a little different and complaining about **Fizzler** rather than **Fizzler.Systems.HtmlAgilityPack**:

> `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3277: Found conflicts between different versions of "Fizzler" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.`

I think the issue here might be that **Fizzler.Systems.HtmlAgilityPack** incorrectly lists **Fizzler** 1.0.0 as a dependency instead of 1.1.0:

https://github.com/atifaziz/Fizzler/blob/a649567321b67f6b56757465365f444e717fdb13/Fizzler.Systems.HtmlAgilityPack.nuspec#L18

A workaround is to explicitly upgrade **Fizzler** to 1.1.0 after installing **Fizzler.Systems.HtmlAgilityPack**. @Spongman, does that make the warning go away for you too?

**Comment by atifaziz** [comment]
Fixed by 17b6fb5d9d8e90c7be38ee115c1a3654e0488f1e.
